name: Sync Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: "https://github.com/Vendicated/Vencord.git"
          upstream_branch: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
